# Este é o formato correto para o seu arquivo .streamlit/secrets.toml
# Copie e cole todo este conteúdo na área de "Secrets" da sua aplicação no Streamlit Cloud.

[firebase_credentials]
type = "service_account"
project_id = "controle-de-aso"
private_key_id = "f72941cf8aca7dd130e03a1d966cb6b90beecc42"

# A chave privada deve estar entre aspas triplas para preservar as quebras de linha.
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCgnzP6RZg8X6r4
xBuWA0ksYovccSkPiVluL89kOfWRXqPt8tNUcWSFsjWPNbNucT9caUD3AX8Z9G6M
6V6JrAfGREusIE+b7vkDRE8tBOjDSwz12pVVRu6QHNknHZsliRbDICS19H8zLm2T
fWqQ6XQZ4ohQJQc7YfDPxEjD+ZaeVDJRrdaTwITzlesSSRJsDlvpNYNnzlE9vX3o
XmqefV6feR3YyQQdS96TzU8aotdB73JMys/l6ACQ8+Bo6Gt8hTVFSusbcvvf19cE
wMazOf7EEYD1WoZRlashi1VGuIf1EIMIudMvtfZl3Jth6MlEIVJWvUk2BTp40DSq
mAMJu7iZAgMBAAECggEAAXPZySZJTX0iqK6X/pqiVhprYApN8BayjlffAkMGlif1
nONDR1I3MdZTZwDPUe0IQP0FWgvTaxgAyplvAhkM1kgr1Fn+c6SM7/CgNAIFW4QZ
kTzxeMdJb62IcTLIAmY4+c7Cm4/4eS1ZpFR6sDt251JbH+PAgFL5wIc/4+B6nOKW
XDaiTg+m14QNW411BppqPvZ6zfnyvhPh2PDqFXYFoyhffSbJeVxzZ6vpPwLRiXpn
yPNhsdD8LgepAJZL0bNhdt698y8fNsr7UXANM1ackLtNMNJghMRtWrCM6X4F9Fzt
wVcgpRoEqv7qp0NV7ga5aqimZwRw3oYHNREa3qGW4QKBgQDbAvlpiLQH5rp+uoCl
VU8hipZvJ5pd+a3Z1CSlyqOzBp+9QdC9FxpRG8cCcyuhZrg04g3ikXL+IyishVOX
OI9vEGLFVrmyAY06cA3/ZlPX8bhLRtehKlDNu6XWNultBs1965J/Pqz4HyzNC0ri
EeNbkCcx4SxYMyFkUMVmQB/4zQKBgQC7v7uwahh7Gyg4ZGOtR13RPlgNbj1uNx7v
dTp6XuQjdNliz5RfJjClUSgrt0aYf/TAJIv7f6VjnDmfexDEJA2/eaQfLV4eteRW
Iu/W03WZbVSixEuaXUkhvTDTtGiKfnAt43etHITq1R7S3kCp2PqIdsqePgWROcbU
xfZY8SYu/QKBgQC8EePH4mJm3pWLufA7CfT34qCoNyPySzQleG04CbllROzrgpcT
qcEpoWbWDbyLzz+j+fLeevR6lAqbi6pqk2FoiHOo7n5sA7UZV5xNk7uwFpyh1+XX
OhVFdjxEpcbxnwPbe+3DYzj5oRvBwE6/r4jD2hguVyTTYKTuFgZNdgd+iQKBgA1L
oZ33lW46WRnNOiXONP2ZXaDt2pnQe3dXpOF/kMZWAwL1Ujt+t9ktKxwVaYFpJkrp
C6SuwGaSbJ43l9Nb/kE9+vpeOxkPpnDXHobnCJ/p1yGDpxryWjhybl+/mduc4pLN
Ve9DYsJCf2FNbeTZQbyiNO0J1VkYb1UoA67+vMZ9AoGBAKQ8djOSa41E4cPp7Eg7
XiF/fJFo7J2rvpZJH7jRrAGOLeiYgmWwnKILJR1xS5/jItA3/kol6ffdAvqxxBVc
ECKEPB59mDSHK6L+28Y1XBMfa/aDZ3z/FKwy5DTcrZYz7peyvgfQs1OLxjYEJYvm
dTszLnfQ9d82aPEUhiRqo6sm
-----END PRIVATE KEY-----
"""

client_email = "firebase-adminsdk-fbsvc@controle-de-aso.iam.gserviceaccount.com"
client_id = "112038247688720865515"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40controle-de-aso.iam.gserviceaccount.com"
storage_bucket_url = "controle-de-aso.firebasestorage.app"

[firebase_config]
apiKey = "AIzaSyCUFHxsaX6RjFXX_obv2KYRSKTU7D-LyTc"
authDomain = "controle-de-aso.firebaseapp.com"
projectId = "controle-de-aso"
storageBucket = "controle-de-aso.firebasestorage.app"
messagingSenderId = "622524253639"
appId = "1:622524253639:web:c4aab01e4dcb1491c585e2"
databaseURL = ""
